export const BOOK_COLLECTION_NAME = 'books'
export const MEMBER_COLLECTION_NAME = 'members'
export const LOAN_COLLECTION_NAME = 'loans'
export const LIBRARY_COLLECTION_NAME = 'libraries'
export const BILL_COLLECTION_NAME = 'bills'
